import React, { useState } from 'react';
import { BatchPRReviewResponse, FileReviewResult } from '../types/review.types.js';
import IssueBadge from './IssueBadge';

interface PRResultsProps {
  result: BatchPRReviewResponse;
  onBack: () => void;
  onPostComment?: (commentBody: string) => Promise<void>;
}

/**
 * PRResults Component
 * Displays batch PR review results with per-file breakdowns
 */
export default function PRResults({ result, onBack, onPostComment }: PRResultsProps) {
  const [isPostingComment, setIsPostingComment] = useState(false);
  const [postCommentError, setPostCommentError] = useState<string | null>(null);
  const [commentPosted, setCommentPosted] = useState(false);
  
  const handlePostComment = async () => {
    if (!onPostComment) return;
    
    try {
      setIsPostingComment(true);
      setPostCommentError(null);
      
      // Format review as markdown comment
      const { overallSummary, filesReviewed } = result;
      
      let commentBody = '## 🔍 CodeRev - Automated Code Review\n\n';
      
      // Summary section
      commentBody += `### Summary\n`;
      commentBody += `- **Files Reviewed:** ${filesReviewed.length}\n`;
      commentBody += `- **Total Issues:** ${overallSummary.totalIssues}\n`;
      commentBody += `- **Errors:** ${overallSummary.totalErrors} | **Warnings:** ${overallSummary.totalWarnings} | **Info:** ${overallSummary.totalInfo}\n\n`;
      
      // Files with issues section
      if (filesReviewed.length > 0) {
        commentBody += `### Reviewed Files\n`;
        
        filesReviewed.forEach((file, index) => {
          const { summary, issues, file: fileInfo } = file;
          commentBody += `\n**${index + 1}. ${fileInfo.fileName}** (${fileInfo.language})\n`;
          commentBody += `- Path: \`${fileInfo.filePath}\`\n`;
          commentBody += `- Change: ${fileInfo.changeType} | +${fileInfo.additions} -${fileInfo.deletions}\n`;
          commentBody += `- Issues: ${summary.totalIssues}\n`;
          
          if (summary.totalIssues > 0) {
            commentBody += `\n#### Issues:\n`;
            issues.forEach(issue => {
              const severityEmoji = issue.severity === 'error' ? '🔴' : issue.severity === 'warning' ? '🟡' : '🔵';
              commentBody += `\n${severityEmoji} **${issue.title}** (Line ${issue.lineNumber || 'N/A'})\n`;
              commentBody += `> ${issue.description}\n`;
              if (issue.suggestedFix) {
                commentBody += `\n**Suggested Fix:** ${issue.suggestedFix}\n`;
              }
            });
          } else {
            commentBody += `✅ No issues found\n`;
          }
        });
      }
      
      commentBody += `\n---\n*Review generated by CodeRev*`;
      
      await onPostComment(commentBody);
      setCommentPosted(true);
      
      // Reset message after 5 seconds
      setTimeout(() => setCommentPosted(false), 5000);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Failed to post comment';
      setPostCommentError(errorMsg);
    } finally {
      setIsPostingComment(false);
    }
  };
  
  if (!result.success) {
    return (
      <div className="pr-results-error">
        <div className="error-card">
          <h2>❌ Review Failed</h2>
          <p className="error-message">{result.error}</p>
          <button onClick={onBack} className="back-btn">
            ← Back
          </button>
        </div>
      </div>
    );
  }

  const { overallSummary, filesReviewed, prUrl, prNumber, repository } = result;
  const filesWithIssues = filesReviewed.filter(f => f.summary.totalIssues > 0);

  return (
    <div className="pr-results-container">
      {/* Header */}
      <div className="pr-results-header">
        <div className="header-buttons">
          <button onClick={onBack} className="pr-back-button">
            ← Back
          </button>
          {onPostComment && (
            <button 
              onClick={handlePostComment}
              disabled={isPostingComment || commentPosted}
              className="pr-post-comment-button"
              title={commentPosted ? 'Comment posted!' : 'Post review as GitHub comment'}
            >
              {isPostingComment ? '📤 Posting...' : commentPosted ? '✅ Posted!' : '💬 Post as Comment'}
            </button>
          )}
        </div>
        <div className="pr-title-section">
          <h1 className="pr-title">Pull Request Review</h1>
          {prNumber && repository && (
            <p className="pr-info-item">
              {repository} <span className="pr-number">#{prNumber}</span>
            </p>
          )}
          <p className="pr-info-value">{prUrl}</p>
        </div>
      </div>
      
      {/* Error/Success Messages */}
      {postCommentError && (
        <div className="pr-error-message">
          <span>❌ {postCommentError}</span>
          <button onClick={() => setPostCommentError(null)} className="close-btn">×</button>
        </div>
      )}

      {/* Overall Summary Stats */}
      <div className="pr-summary-stats">
        <div className="stat-card">
          <div className="stat-label">Files Reviewed</div>
          <div className="stat-value">{filesReviewed.length}</div>
          <div className="stat-detail">{filesWithIssues.length} with issues</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Total Issues</div>
          <div className="stat-value">{overallSummary.totalIssues}</div>
        </div>
        <div className="stat-card error">
          <div className="stat-label">Errors</div>
          <div className="stat-value">{overallSummary.totalErrors}</div>
        </div>
        <div className="stat-card warning">
          <div className="stat-label">Warnings</div>
          <div className="stat-value">{overallSummary.totalWarnings}</div>
        </div>
        <div className="stat-card info">
          <div className="stat-label">Info</div>
          <div className="stat-value">{overallSummary.totalInfo}</div>
        </div>
      </div>

      {/* Files List */}
      {filesReviewed.length === 0 ? (
        <div className="no-files-message">
          <p>No reviewable files found in this PR.</p>
        </div>
      ) : (
        <div className="files-list">
          <h2>Files Changed</h2>
          {filesReviewed.map((fileResult, index) => (
            <FileReviewCard
              key={index}
              fileResult={fileResult}
              index={index + 1}
              total={filesReviewed.length}
            />
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * FileReviewCard - Displays review results for a single file
 */
function FileReviewCard({
  fileResult,
  index,
  total,
}: {
  fileResult: FileReviewResult;
  index: number;
  total: number;
}) {
  const { file, issues, summary } = fileResult;
  const hasIssues = summary.totalIssues > 0;

  return (
    <div className={`file-review-card ${hasIssues ? 'with-issues' : 'clean'}`}>
      {/* File Header */}
      <div className="file-header">
        <div className="file-title">
          <span className="file-number">{index}/{total}</span>
          <span className="file-name">{file.fileName}</span>
          <span className={`file-type ${file.language}`}>{file.language}</span>
        </div>
        <div className="file-stats">
          <span className="change-type" data-type={file.changeType}>
            {file.changeType === 'added' ? '✨ Added' : '✏️ Modified'}
          </span>
          <span className="changes-count">
            +{file.additions} -{file.deletions}
          </span>
        </div>
      </div>

      {/* File Path */}
      <div className="file-path">{file.filePath}</div>

      {/* File Summary */}
      <div className="file-summary">
        {hasIssues ? (
          <>
            <span className="issues-count">
              {summary.totalIssues} issue{summary.totalIssues !== 1 ? 's' : ''} found
            </span>
            <div className="issues-breakdown">
              {summary.errorCount > 0 && (
                <span className="breakdown-item error">
                  {summary.errorCount} error{summary.errorCount !== 1 ? 's' : ''}
                </span>
              )}
              {summary.warningCount > 0 && (
                <span className="breakdown-item warning">
                  {summary.warningCount} warning{summary.warningCount !== 1 ? 's' : ''}
                </span>
              )}
              {summary.infoCount > 0 && (
                <span className="breakdown-item info">
                  {summary.infoCount} info
                </span>
              )}
            </div>
          </>
        ) : (
          <span className="no-issues">✅ No issues found</span>
        )}
      </div>

      {/* Issues List */}
      {hasIssues && (
        <div className="file-issues">
          {issues.map((issue) => (
            <div key={issue.id} className="issue-item" data-category={issue.category}>
              <div className="issue-header">
                <IssueBadge severity={issue.severity} />
                <h4 className="issue-title">{issue.title}</h4>
              </div>
              <p className="issue-description">{issue.description}</p>
              {issue.suggestedFix && (
                <div className="issue-fix">
                  <strong>Fix:</strong> {issue.suggestedFix}
                </div>
              )}
              {issue.lineNumber && (
                <div className="issue-line">
                  Line {issue.lineNumber}
                  {issue.codeSnippet && (
                    <pre className="code-snippet">{issue.codeSnippet}</pre>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
